// Generated by WorksOnMyDB. Edit your schema file instead of this output.

export interface Users {
  id: number;
  email: string;
  created_at: Date | string;
}

export interface Posts {
  id: number;
  user_id: number;
  title: string;
  body: string;
  published: boolean;
  metadata?: unknown;
}

export interface Tables {
  users: Users;
  posts: Posts;
}
